os: linux
dist: xenial
language: python

notifications:
    email: false

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"


before_install:
    - python --version
    - pip install -U pip
    - pip install pytest
    - pip install -r requirements.txt

install:
    - pip install .

script:
    - cd main/tests
    - python -m "pytest" -v

